function build_estimator(step)
% BUILD_ESTIMATOR  Restore the HGQ2 harmonic estimator (one-cycle Residual-BLS)
% and the FFT+HGQ2 hybrid fusion in PV_MEV/EV System/PFC Control.
%
%   build_estimator()          all steps and save
%   build_estimator('inspect') only print the current state
%
% Estimation sources (Multiport Switch, estimation_src in config.csv):
%   1 FFT 1-cycle  2 FFT 10-cycle  3 HGQ2 one-cycle (raw)  4 half-cycle (n/a)
%   5 RLS          6 FFT1 + HGQ2 hybrid fusion (package alpha, watchdog)
% The ONNX model runs through OnnxRunner (MATLAB System block -> Python
% onnxruntime via onnx_bridge.py).  Model file: FFT_HGQ_BLS_FPGA/artifacts/
% harmonic_residual_bls_simulink.onnx (input [1 80] normalized window ->
% [1 8] phasor components), decoded by harmonic_postprocess8_block to
% [A1 A3 A5 A7 delta3 delta5 delta7] exactly as in the packaged R2025a model.
if nargin < 1, step = 'all'; end
mdir = fileparts(mfilename('fullpath')); cd(mdir); addpath(mdir);
mdl = 'PV_MEV'; load_system(mdl);
pc = [mdl '/EV System/PFC Control'];
one = [pc '/One  Cycle Model Prediction'];      % two spaces, as in the model
onnx_file = fullfile(fileparts(fileparts(mdir)), 'FFT_HGQ_BLS_FPGA', 'artifacts', 'harmonic_residual_bls_simulink.onnx');
assert(isfile(onnx_file), 'missing %s', onnx_file);
if strcmp(step, 'inspect'), inspect(pc, one); close_system(mdl, 0); return; end

% --- 1. one-cycle subsystem: uncomment, swap the ONNX block, fix post-processing
set_param(one, 'Commented', 'off');
% Goto17 (tag predict_D) stays commented: it duplicates Goto29
old = [one '/ONNX Model Predict'];
if getSimulinkBlockHandle(old) ~= -1
    pos = get_param(old, 'Position'); delete_block(old);
    add_block('simulink/User-Defined Functions/MATLAB System', [one '/ONNX Runner'], 'System', 'OnnxRunner', 'Position', pos);
end
set_param([one '/ONNX Runner'], 'ModelFile', ['''' strrep(onnx_file, '\', '/') ''''], 'NumIn', '80', 'NumOut', '8', 'SampleTime', '1/(mm_fund_freq*mm_points_per_cycle)');
relink(one, 'Data Type Conversion', 1, 'ONNX Runner', 1);
relink(one, 'ONNX Runner', 1, 'Data Type Conversion1', 1);
set_param([one '/u_buff'], 'N', 'mm_points_per_cycle', 'V', 'mm_sampling_overlap');
set_param([one '/Sampling1'], 'SampleTime', '1/(mm_fund_freq*mm_points_per_cycle)');
set_param([one '/Constant1'], 'Value', '1');                 % EMA alpha = 1 (no smoothing), as packaged
set_mlfcn([one '/MATLAB Function3'], postprocess_code());
set_mlfcn([one '/MATLAB Function'], cyclenorm_code());
% --- 2. make sure the subsystem outputs reach the model_1 Goto tags
ensure_goto(pc, one, 1, 'model_1_amp');
ensure_goto(pc, one, 2, 'model_1_phase');
% --- 3. hybrid fusion (FFT1 + HGQ2) -> estimation_src 6
hb = [pc '/HGQ FFT-DL Hybrid'];
if getSimulinkBlockHandle(hb) == -1
    add_block('simulink/User-Defined Functions/MATLAB Function', hb, 'Position', [5300 900 5420 1060]);
    set_mlfcn(hb, hybrid_code(), {'fft_amplitude', '[4 1]'; 'fft_phase', '[3 1]'; 'dl_amplitude', '[4 1]'; 'dl_phase', '[3 1]'; ...
        'alpha', '[4 1]'; 'minimum_ratio', '1'; 'amplitude_out', '[4 1]'; 'phase_out', '[3 1]'; 'dl_accepted', '1'});
    src = {'fft_1_amp', 'fft_1_phase', 'model_1_amp', 'model_1_phase'};
    for i = 1:4
        f = sprintf('%s/From_hyb%d', pc, i);
        add_block('simulink/Signal Routing/From', f, 'GotoTag', src{i}, 'Position', [5150 890 + 40 * i, 5250 910 + 40 * i]);
        r = sprintf('%s/Reshape_hyb%d', pc, i);
        add_block('simulink/Math Operations/Reshape', r, 'OutputDimensionality', 'Column vector (2-D)', 'Position', [5265 892 + 40 * i, 5285 908 + 40 * i]);
        add_line(pc, sprintf('From_hyb%d/1', i), sprintf('Reshape_hyb%d/1', i)); add_line(pc, sprintf('Reshape_hyb%d/1', i), sprintf('HGQ FFT-DL Hybrid/%d', i));
    end
    add_block('simulink/Sources/Constant', [pc '/HGQ fusion alpha'], 'Value', 'hgq_fusion_alpha(:)', 'Position', [5150 1090 5250 1110]);
    add_block('simulink/Sources/Constant', [pc '/HGQ minimum ratio'], 'Value', 'hgq_min_ratio', 'Position', [5150 1130 5250 1150]);
    add_line(pc, 'HGQ fusion alpha/1', 'HGQ FFT-DL Hybrid/5'); add_line(pc, 'HGQ minimum ratio/1', 'HGQ FFT-DL Hybrid/6');
    add_block('simulink/Signal Routing/Goto', [pc '/Goto_hyb_amp'], 'GotoTag', 'hybrid_amp', 'Position', [5480 920 5580 940]);
    add_block('simulink/Signal Routing/Goto', [pc '/Goto_hyb_phase'], 'GotoTag', 'hybrid_phase', 'Position', [5480 970 5580 990]);
    add_block('simulink/Sinks/Terminator', [pc '/T_hyb'], 'Position', [5480 1020 5500 1040]);
    add_line(pc, 'HGQ FFT-DL Hybrid/1', 'Goto_hyb_amp/1'); add_line(pc, 'HGQ FFT-DL Hybrid/2', 'Goto_hyb_phase/1'); add_line(pc, 'HGQ FFT-DL Hybrid/3', 'T_hyb/1');
end
% --- 4. extend both multiport switches to 6 data inputs (6 = hybrid)
sw = {'Multiport Switch', 'hybrid_amp', 'From_sw_hamp'; 'Multiport Switch1', 'hybrid_phase', 'From_sw_hph'};
for i = 1:2
    b = [pc '/' sw{i, 1}];
    if str2double(get_param(b, 'Inputs')) < 6
        set_param(b, 'Inputs', '6');
        p = get_param(b, 'Position');
        add_block('simulink/Signal Routing/From', [pc '/' sw{i, 3}], 'GotoTag', sw{i, 2}, 'Position', [p(1) - 175, p(4) + 15, p(1) - 45, p(4) + 39]);
        add_line(pc, [sw{i, 3} '/1'], [sw{i, 1} '/7'], 'autorouting', 'on');
    end
end
inspect(pc, one);
save_system(mdl); close_system(mdl);
fprintf('[build_estimator] PV_MEV saved\n');
end

% -------------------------------------------------------------------------
function inspect(pc, one)
fprintf('One-cycle subsystem commented=%s\n', get_param(one, 'Commented'));
b = find_system(one, 'SearchDepth', 1, 'LookUnderMasks', 'all', 'IncludeCommented', 'on');
for i = 2:numel(b)
    bt = get_param(b{i}, 'BlockType'); extra = '';
    if strcmp(bt, 'MATLABSystem'), extra = [' system=' get_param(b{i}, 'System') ' NumIn=' get_param(b{i}, 'NumIn') ' Ts=' get_param(b{i}, 'SampleTime')]; end
    if strcmp(bt, 'Buffer'), extra = [' N=' get_param(b{i}, 'N') ' V=' get_param(b{i}, 'V')]; end
    fprintf('   [%s] %s%s\n', bt, get_param(b{i}, 'Name'), extra);
end
for s = {'Multiport Switch', 'Multiport Switch1'}
    ph = get_param([pc '/' s{1}], 'PortHandles'); fprintf('%s: %d data inputs:', s{1}, numel(ph.Inport) - 1);
    for i = 2:numel(ph.Inport)
        l = get_param(ph.Inport(i), 'Line'); nm = '-';
        if l ~= -1, sb = get_param(l, 'SrcBlockHandle'); if sb ~= -1, try, nm = get_param(sb, 'GotoTag'); catch, nm = get_param(sb, 'Name'); end, end, end
        fprintf(' %d:%s', i - 1, nm);
    end
    fprintf('\n');
end
end

function relink(sub, srcb, srcp, dstb, dstp)
ph = get_param([sub '/' dstb], 'PortHandles'); l = get_param(ph.Inport(dstp), 'Line');
if l ~= -1, delete_line(l); end
add_line(sub, sprintf('%s/%d', srcb, srcp), sprintf('%s/%d', dstb, dstp), 'autorouting', 'on');
end

function ensure_goto(pc, sub, port, tag)
g = find_system(pc, 'SearchDepth', 1, 'LookUnderMasks', 'all', 'IncludeCommented', 'on', 'BlockType', 'Goto', 'GotoTag', tag);
if isempty(g), error('Goto %s not found', tag); end
set_param(g{1}, 'Commented', 'off');
lh = get_param(g{1}, 'LineHandles');
if lh.Inport == -1
    add_line(pc, sprintf('%s/%d', get_param(sub, 'Name'), port), [get_param(g{1}, 'Name') '/1'], 'autorouting', 'on');
end
end

function set_mlfcn(blk, code, sizes)
rt = sfroot; ch = rt.find('-isa', 'Stateflow.EMChart', 'Path', blk);
if isempty(ch), error('MATLAB Function chart not found: %s', blk); end
ch = ch(1); ch.Script = code;
if nargin > 2
    for i = 1:size(sizes, 1)
        d = ch.find('-isa', 'Stateflow.Data', 'Name', sizes{i, 1});
        if ~isempty(d), d(1).Props.Array.Size = sizes{i, 2}; d(1).DataType = 'Inherit: Same as Simulink'; end
    end
end
end

function s = cyclenorm_code()
s = sprintf(['function [x_norm, A] = CycleNorm(x)\n' ...
    '%%#codegen\n' ...
    '%% HGQ2 contract: normalize the 80-sample window by its peak (side channel A).\n' ...
    'A = max(abs(x));\n' ...
    'A = max(A, 1e-6);\n' ...
    'x_norm = x / A;\n']);
end

function s = postprocess_code()
s = sprintf(['function y_post = harmonic_postprocess8_block(y_encoded, window_peak, ema_alpha, reset)\n' ...
'%%#codegen\n' ...
'%% Decode [c1,s1,c3,s3,c5,s5,c7,s7] to the legacy MPCC vector [A1,A3,A5,A7,delta3,delta5,delta7]\n' ...
'%% (same as the packaged FFT_HGQ_BLS model; window_peak is the CycleNorm side channel).\n' ...
'persistent state initialized\n' ...
'if isempty(initialized)\n' ...
'    state = zeros(8, 1, ''single'');\n' ...
'    initialized = false;\n' ...
'end\n' ...
'y = zeros(8, 1, ''single'');\n' ...
'for index = 1:8\n' ...
'    y(index) = single(y_encoded(index));\n' ...
'end\n' ...
'alpha = min(max(single(ema_alpha), single(0)), single(1));\n' ...
'if ~initialized || reset ~= 0\n' ...
'    state = y;\n' ...
'    initialized = true;\n' ...
'else\n' ...
'    state = alpha * y + (single(1) - alpha) * state;\n' ...
'end\n' ...
'peak = max(abs(single(window_peak)), single(1e-6));\n' ...
'order_scale = single([1.0; 0.25; 0.20; 0.15]);\n' ...
'amplitude = zeros(4, 1, ''single'');\n' ...
'phase = zeros(4, 1, ''single'');\n' ...
'for harmonic_index = 1:4\n' ...
'    component = 2 * harmonic_index - 1;\n' ...
'    real_part = state(component);\n' ...
'    imag_part = state(component + 1);\n' ...
'    amplitude(harmonic_index) = peak * order_scale(harmonic_index) * hypot(real_part, imag_part);\n' ...
'    phase(harmonic_index) = atan2(imag_part, real_part);\n' ...
'end\n' ...
'orders = single([3; 5; 7]);\n' ...
'y_post = zeros(7, 1, ''single'');\n' ...
'y_post(1:4) = amplitude;\n' ...
'for index = 1:3\n' ...
'    relative = phase(index + 1) - orders(index) * phase(1);\n' ...
'    y_post(index + 4) = atan2(sin(relative), cos(relative));\n' ...
'end\n' ...
'end\n']);
end

function s = hybrid_code()
s = sprintf(['function [amplitude_out, phase_out, dl_accepted] = harmonic_hybrid_fusion_block(fft_amplitude, fft_phase, dl_amplitude, dl_phase, alpha, minimum_ratio)\n' ...
'%%#codegen\n' ...
'%% Fuse FFT (1-cycle) and HGQ2 harmonic estimates in Cartesian coordinates with a\n' ...
'%% per-order weight alpha; falls back to FFT when the DL output fails the watchdog.\n' ...
'amplitude_out = zeros(4, 1, ''single'');\n' ...
'phase_out = zeros(3, 1, ''single'');\n' ...
'dl_accepted = false;\n' ...
'fft_amp = zeros(4, 1, ''single''); dl_amp = zeros(4, 1, ''single''); weight = zeros(4, 1, ''single'');\n' ...
'fft_phi = zeros(3, 1, ''single''); dl_phi = zeros(3, 1, ''single'');\n' ...
'for index = 1:4\n' ...
'    fft_amp(index) = single(fft_amplitude(index)); dl_amp(index) = single(dl_amplitude(index));\n' ...
'    weight(index) = min(max(single(alpha(index)), single(0)), single(1));\n' ...
'end\n' ...
'for index = 1:3\n' ...
'    fft_phi(index) = single(fft_phase(index)); dl_phi(index) = single(dl_phase(index));\n' ...
'end\n' ...
'ratio = max(single(minimum_ratio), single(0));\n' ...
'valid = true;\n' ...
'for index = 1:4\n' ...
'    valid = valid && isfinite(dl_amp(index)) && dl_amp(index) >= single(0);\n' ...
'end\n' ...
'for index = 1:3\n' ...
'    valid = valid && isfinite(dl_phi(index));\n' ...
'end\n' ...
'valid = valid && dl_amp(1) > single(1e-5);\n' ...
'valid = valid && max(dl_amp(2:4)) <= single(4) * max(dl_amp(1), single(1e-5));\n' ...
'if ~valid\n' ...
'    amplitude_out = fft_amp; phase_out = fft_phi;\n' ...
'    return\n' ...
'end\n' ...
'dl_accepted = true;\n' ...
'amplitude_out(1) = (single(1) - weight(1)) * fft_amp(1) + weight(1) * dl_amp(1);\n' ...
'for index = 1:3\n' ...
'    harmonic = index + 1;\n' ...
'    real_part = (single(1) - weight(harmonic)) * fft_amp(harmonic) * cos(fft_phi(index)) + weight(harmonic) * dl_amp(harmonic) * cos(dl_phi(index));\n' ...
'    imag_part = (single(1) - weight(harmonic)) * fft_amp(harmonic) * sin(fft_phi(index)) + weight(harmonic) * dl_amp(harmonic) * sin(dl_phi(index));\n' ...
'    amplitude_out(harmonic) = hypot(real_part, imag_part);\n' ...
'    phase_out(index) = atan2(imag_part, real_part);\n' ...
'    if amplitude_out(harmonic) < ratio * max(amplitude_out(1), single(1e-5))\n' ...
'        amplitude_out(harmonic) = single(0); phase_out(index) = fft_phi(index);\n' ...
'    end\n' ...
'end\n' ...
'end\n']);
end
