function build_supp(step)
% BUILD_SUPP  Supplementary experiments for the HIL-SAR paper (2026-09-06), three model changes:
%
%   build_supp('gain')      shape 8 = multiplicative gain error: the injector's generator gets the real value y as an
%                           input (Rate Transition to Ts_inj) and adds dy = amp * y, so y_int = (1 + amp) * y_real.
%                           Applied to the library block MyLibrary/Disturbance Injector (covers the linked inj_ch1..3)
%                           and to the unlinked copies inside Charger Stage (inj_Vbat, inj_Ibat).
%   build_supp('bumpless')  mitigation mask bit M9 (512): the Vdc / Vbat correction amounts are introduced and removed
%                           through a slew-rate limiter (500 V/s bus, 100 V/s battery) whenever the estimate comes from the detector's
%                           amplitude head (physics estimate unavailable); the physics estimate itself already tracks the bias.
%                           MPCC_R_B = mask 949.  (A limiter on the physics path delayed the correction and caused OV.)
%   build_supp('oracle')    det_force = 2: the mitigation flags come from the injection definition itself
%                           (inj_channel / inj_shape / inj_t_on / inj_dwell, noise slot excluded) instead of the
%                           detector -> separates detection delay from the mitigation's own limit (MPCC_R_OR).
%   build_supp('grid')      replace the utility '120kV 2500MVA' Three-Phase Source by a Three-Phase Programmable Voltage
%                           Source (same 120 kV / Fnom, internal impedance moved to a series RL branch R 0.8929 / L 16.58 mH)
%                           so benign grid events (amplitude / frequency step at grid_var_t0, harmonic injection) happen
%                           inside a run instead of at the snapshot time.  Snapshot with VariationEntity = None;
%                           run_injection's prepare() sets the variation from the GRID struct per run.
%   build_supp()            all three (not 'grid'), then save.  All steps change the model structure: redo the snapshots.
if nargin < 1, step = 'all'; end
mdir = fileparts(mfilename('fullpath')); cd(mdir); addpath(mdir);
mdl = 'PV_MEV'; load_system(mdl);
ev = [mdl '/EV System']; pc = [ev '/PFC Control']; chg = [ev '/Charger Stage'];
if any(strcmp(step, {'gain', 'all'})), do_gain(mdl, ev, chg); end
if any(strcmp(step, {'bumpless', 'oracle', 'all'})), do_mitigation(pc, chg); end
if strcmp(step, 'grid'), do_grid(mdl); end
save_system(mdl); close_system(mdl);
lib = 'MyLibrary'; if bdIsLoaded(lib), save_system(lib); close_system(lib); end
fprintf('[build_supp] %s applied, PV_MEV (and MyLibrary) saved\n', step);
end

% ================================================================= gain
function do_gain(mdl, ev, chg)
lib = 'MyLibrary'; load_system(lib); set_param(lib, 'Lock', 'off');
patch_injector([lib '/Disturbance Injector']);
for b = {[chg '/inj_Vbat'], [chg '/inj_Ibat'], [ev '/inj_ch1'], [ev '/inj_ch2'], [ev '/inj_ch3']}
    st = get_param(b{1}, 'LinkStatus');
    if any(strcmp(st, {'resolved', 'implicit'}))
        fprintf('   [gain] %s is library-linked (%s), covered by the library edit\n', b{1}, st);
    else
        patch_injector(b{1});
    end
end
end

function patch_injector(p)
if getSimulinkBlockHandle([p '/RT_y']) ~= -1, fprintf('   [gain] %s already patched\n', p); return; end
add_block('simulink/Signal Attributes/Rate Transition', [p '/RT_y'], 'OutPortSampleTime', 'Ts_inj', 'Integrity', 'on', 'Deterministic', 'on', 'Position', [100 130 140 160]);
set_mlfcn([p '/gen'], gen_code(), {'y', '1'});
add_line(p, 'y_real/1', 'RT_y/1', 'autorouting', 'on');
ph = get_param([p '/gen'], 'PortHandles');
add_line(p, get_param([p '/RT_y'], 'PortHandles').Outport(1), ph.Inport(end), 'autorouting', 'on');
fprintf('   [gain] %s: gen input y added (%d inputs)\n', p, numel(ph.Inport));
end

function s = gen_code()
s = sprintf([ ...
'function dy = gen(t, ch_id, channel, shape, amp, k, f, ph, period, duty, t_on, dwell, K_hall, y)\n' ...
'%% Equivalent measurement bias dy(t).  channel/shape/amp/k/f/ph are 1x3 so two\n' ...
'%% channels can be disturbed at once (E-MUL-01) plus a noise slot; an entry\n' ...
'%% with channel 0 is off.  Shape 7 = uniform white noise of amplitude amp\n' ...
'%% (measurement noise, a benign negative sample for the detector).\n' ...
'%% Shape 8 = multiplicative gain error: dy = amp * y (y = real value), i.e. y_int = (1 + amp) * y_real.\n' ...
'dy = 0;\n' ...
'tau = t - t_on;\n' ...
'if tau < 0 || tau >= dwell, return; end\n' ...
'for i = 1:numel(channel)\n' ...
'    if channel(i) ~= ch_id, continue; end\n' ...
'    a = amp(i);\n' ...
'    switch shape(i)\n' ...
'        case 1, d = a;\n' ...
'        case 2, d = sign(a)*min(abs(a), k(i)*tau);\n' ...
'        case 3, d = a*sin(2*pi*f(i)*t + ph(i)*pi/180);\n' ...
'        case 4, x = mod(tau, period)/period; d = a*(1 - abs(2*x - 1));\n' ...
'        case 5, d = a*double(mod(tau, period) < duty*period);\n' ...
'        case 6, d = K_hall*(0.2 + 0.5*sin(2*pi*f(i)*t));\n' ...
'        case 7, d = a*(2*rand - 1);\n' ...
'        case 8, d = a*y;\n' ...
'        otherwise, d = 0;\n' ...
'    end\n' ...
'    dy = dy + d;\n' ...
'end\n']);
end

% ================================================================= bumpless (M9) + oracle (force = 2)
function do_mitigation(pc, chg)
mit = [pc '/Mitigation']; cc = [chg '/chg_corr'];
% oracle inputs (constants from init_paras: inj_channel, inj_shape, inj_t_on, inj_dwell)
truth = {'inj_ch', 'inj_channel', '[1 3]'; 'inj_sh', 'inj_shape', '[1 3]'; 'inj_t0', 'inj_t_on', '1'; 'inj_dw', 'inj_dwell', '1'};
set_mlfcn(mit, mitigation_code(), truth(:, [1 3]));
if getSimulinkBlockHandle([pc '/mit_inj_ch']) == -1
    ph = get_param(mit, 'PortHandles'); n0 = numel(ph.Inport) - 4;
    for i = 1:4
        add_block('simulink/Sources/Constant', sprintf('%s/mit_%s', pc, truth{i, 1}), 'Value', truth{i, 2}, 'Position', [5100 1900 + 30 * i, 5180 1920 + 30 * i]);
        add_line(pc, sprintf('mit_%s/1', truth{i, 1}), sprintf('Mitigation/%d', n0 + i), 'autorouting', 'on');
    end
    fprintf('   [oracle] Mitigation: 4 truth inputs added (ports %d..%d)\n', n0 + 1, n0 + 4);
end
set_mlfcn(cc, charger_code(), truth(:, [1 3]));
if getSimulinkBlockHandle([chg '/cc_inj_ch']) == -1
    ph = get_param(cc, 'PortHandles'); n0 = numel(ph.Inport) - 4;
    for i = 1:4
        add_block('simulink/Sources/Constant', sprintf('%s/cc_%s', chg, truth{i, 1}), 'Value', truth{i, 2}, 'Position', [480 900 + 30 * i, 540 920 + 30 * i]);
        add_line(chg, sprintf('cc_%s/1', truth{i, 1}), sprintf('chg_corr/%d', n0 + i), 'autorouting', 'on');
    end
    fprintf('   [oracle] chg_corr: 4 truth inputs added (ports %d..%d)\n', n0 + 1, n0 + 4);
end
fprintf('   [bumpless] M9 slew-limited fallback corrections in Mitigation (500 V/s) and chg_corr (100 V/s)\n');
end

function s = mitigation_code()
s = sprintf([ ...
'function [Vdc_fb, Iref_out, Vin_out, iL_out, hold, g_alpha, dbg] = mitigation(flags, amps, Vdc, Vac, th, iL, Iref, chg, mask, use_det, force, Ts, t_ramp, tnow, t_arm, inj_ch, inj_sh, inj_t0, inj_dw)\n' ...
'%%#codegen\n' ...
'%% Detection-conditioned signal corrections for MPCC_R (build_mitigation.m, build_supp.m).  Runs at Ts_Control.\n' ...
'%% flags/amps: detector channel flags and signed normalized amplitudes (Vdc Vac Iac Vbat Ibat)\n' ...
'%% chg = [Vbat_real Ibat_real Vbat_int Ibat_int D_dcdc state Iref_bat P_charge Idc]\n' ...
'%% force = 1: every flag on (MPCC_R_ON); force = 2: oracle flags from the injection definition (MPCC_R_OR)\n' ...
'%% M9 (512): slew-limited introduction / removal of the Vdc correction (bumpless), MPCC_R_B\n' ...
'persistent g dVf Iref_prev pkp pkn Vamp th_prev init\n' ...
'if isempty(init), g = zeros(1, 5); dVf = 0; Iref_prev = 0; pkp = 0; pkn = 0; Vamp = 0; th_prev = 0; init = 1; end\n' ...
'M = @(k) bitand(uint32(mask), uint32(2^k)) > 0;\n' ...
'f = flags .* (use_det > 0);\n' ...
'if force == 1, f = ones(1, 5); end\n' ...
'if force > 1\n' ...
'    f = zeros(1, 5);\n' ...
'    if tnow >= inj_t0 && tnow < inj_t0 + inj_dw\n' ...
'        for i = 1:3, c = inj_ch(i); if c >= 1 && c <= 5 && inj_sh(i) ~= 7, f(c) = 1; end, end\n' ...
'    end\n' ...
'end\n' ...
'if tnow < t_arm, f = zeros(1, 5); end          %% detector armed only after start-up (det_t_arm)\n' ...
'if f(1) > 0.5, f(4) = 0; f(5) = 0; end         %% priority: a Vdc-chain flag explains the charger-side symptoms (Vbat / Ibat flags are consequences)\n' ...
'%% --- channel gains: Vdc immediate (a measurement correction must track the bias, not ramp), the rest ramp out over t_ramp (M7)\n' ...
'for c = 1:5\n' ...
'    if f(c) > 0.5, g(c) = 1;\n' ...
'    elseif M(7) && c ~= 1, g(c) = max(0, g(c) - Ts / max(t_ramp, Ts));\n' ...
'    else, g(c) = 0; end\n' ...
'end\n' ...
'%% --- Vdc chain: bias estimate dV = Vdc_int - Vdc_true\n' ...
'Vbat_i = chg(3); Ibat_i = chg(4); Ddc = chg(5);\n' ...
'dV_det = amps(1) * 100;\n' ...
'phys_ok = (Ddc > 0.3) && (Ddc < 0.98) && (Ibat_i > 1);\n' ...
'if phys_ok\n' ...
'    dV = Vdc - Vbat_i / Ddc;                    %% charger duty tells the true bus: Vbat = D_dcdc * Vdc_true\n' ...
'else\n' ...
'    dV = dV_det;\n' ...
'end\n' ...
'dV = min(max(dV, -120), 120);\n' ...
'Vdc_fb = Vdc;\n' ...
'if M(9) && ~phys_ok\n' ...
'    %% bumpless: only the amplitude-head fallback is slew-limited (500 V/s); the physics estimate tracks the true bias and\n' ...
'    %% vanishes with it, a rate limit there only delays the correction (E-DC-01b: 50 ms of stale correction -> OV)\n' ...
'    tgt = 0; if g(1) > 0, tgt = dV; end\n' ...
'    lim = 500 * Ts; stp = tgt - dVf; stp = min(max(stp, -lim), lim); dVf = dVf + stp;\n' ...
'    if M(0), Vdc_fb = Vdc - dVf; end\n' ...
'else\n' ...
'    if g(1) > 0, dVf = dVf + (Ts / 0.005) * (dV - dVf); else, dVf = 0; end\n' ...
'    if M(0), Vdc_fb = Vdc - g(1) * dVf; end\n' ...
'end\n' ...
'%% --- Iref amplitude limits (M0 floor, M1 slew) live in the separate block ''Mitigation Iref'' (algebraic loop)\n' ...
'Iref_out = 0 * Iref + Iref_prev * 0;\n' ...
'%% --- Vac chain: PLL-reconstructed feed-forward voltage (peak-to-peak / 2 of the previous cycle)\n' ...
'if th < th_prev - 3                          %% wrap: new cycle\n' ...
'    Vamp = 0.5 * (pkp - pkn); pkp = 0; pkn = 0;\n' ...
'end\n' ...
'th_prev = th; pkp = max(pkp, Vac); pkn = min(pkn, Vac);\n' ...
'Vin_out = Vac;\n' ...
'if M(2) && g(2) > 0 && Vamp > 50, Vin_out = Vac + g(2) * (Vamp * sin(th) - Vac); end\n' ...
'%% --- Iac chain: DC compensation of the predictor current, estimator hold\n' ...
'iL_out = iL;\n' ...
'if M(3), iL_out = iL - g(3) * amps(3) * 20; end\n' ...
'hold = 0;\n' ...
'if M(4) && g(3) > 0, hold = 1; end\n' ...
'%% --- fusion weight towards the HGQ2 estimate while Vac is flagged\n' ...
'g_alpha = 0;\n' ...
'if M(8), g_alpha = g(2); end\n' ...
'dbg = [g(1), dVf, double(phys_ok), Vamp, g(3), hold];\n']);
end

function s = charger_code()
s = sprintf([ ...
'function [Vbat_c, Ibat_c] = chg_corr(Vbat_m, Ibat_m, flags, amps, mask, use_det, force, Ts, t_ramp, tnow, t_arm, Vdc, D_prev, inj_ch, inj_sh, inj_t0, inj_dw)\n' ...
'%%#codegen\n' ...
'%% M5 / M6: remove the detected Vbat / Ibat measurement bias before the CC/CV controller (build_mitigation.m, build_supp.m)\n' ...
'%% force = 2: oracle flags from the injection definition; M9 (512): slew-limited (200 V/s) Vbat correction\n' ...
'persistent g dVf init\n' ...
'if isempty(init), g = zeros(1, 2); dVf = 0; init = 1; end\n' ...
'fl = flags .* (use_det > 0);\n' ...
'if force == 1, fl = ones(1, 5); end\n' ...
'if force > 1\n' ...
'    fl = zeros(1, 5);\n' ...
'    if tnow >= inj_t0 && tnow < inj_t0 + inj_dw\n' ...
'        for i = 1:3, c = inj_ch(i); if c >= 1 && c <= 5 && inj_sh(i) ~= 7, fl(c) = 1; end, end\n' ...
'    end\n' ...
'end\n' ...
'f = fl(4:5);\n' ...
'if tnow < t_arm || fl(1) > 0.5, f = zeros(1, 2); end   %% armed after start-up; a Vdc-chain flag overrides the charger-side flags\n' ...
'ramp = bitand(uint32(mask), uint32(128)) > 0;\n' ...
'for c = 1:2\n' ...
'    if f(c) > 0.5, g(c) = 1;\n' ...
'    elseif ramp, g(c) = max(0, g(c) - Ts / max(t_ramp, Ts));\n' ...
'    else, g(c) = 0; end\n' ...
'end\n' ...
'Vbat_c = Vbat_m; Ibat_c = Ibat_m;\n' ...
'phys_ok = (D_prev > 0.3) && (D_prev < 0.98) && (Ibat_m > 1) && (Vdc > 250);\n' ...
'if phys_ok, dV = Vbat_m - D_prev * Vdc; else, dV = amps(4) * 25; end   %% buck: Vbat = D * Vdc while regulating; detector amplitude as fallback\n' ...
'dV = min(max(dV, -60), 60);\n' ...
'if bitand(uint32(mask), uint32(512)) > 0 && ~phys_ok      %% M9: slew-limited amplitude-head fallback only (100 V/s)\n' ...
'    tgt = 0; if g(1) > 0, tgt = dV; end\n' ...
'    lim = 100 * Ts; stp = tgt - dVf; stp = min(max(stp, -lim), lim); dVf = dVf + stp;\n' ...
'    if bitand(uint32(mask), uint32(32)) > 0, Vbat_c = Vbat_m - dVf; end\n' ...
'else\n' ...
'    if g(1) > 0, dVf = dVf + (Ts / 0.002) * (dV - dVf); else, dVf = 0; end\n' ...
'    if bitand(uint32(mask), uint32(32)) > 0, Vbat_c = Vbat_m - g(1) * dVf; end\n' ...
'end\n' ...
'if bitand(uint32(mask), uint32(64)) > 0, Ibat_c = Ibat_m - g(2) * amps(5) * 8; end\n']);
end

% ================================================================= helpers
function set_mlfcn(blk, code, sizes)
rt = sfroot; ch = rt.find('-isa', 'Stateflow.EMChart', 'Path', blk);
if isempty(ch), error('MATLAB Function chart not found: %s', blk); end
ch = ch(1); ch.Script = code;
if nargin > 2
    for i = 1:size(sizes, 1)
        dd = ch.find('-isa', 'Stateflow.Data', 'Name', sizes{i, 1});
        if ~isempty(dd), dd(1).Props.Array.Size = sizes{i, 2}; dd(1).DataType = 'Inherit: Same as Simulink'; end
    end
end
end

% ================================================================= programmable utility source
function do_grid(mdl)
grid = [mdl sprintf('/600V\nUtlity Grid')]; old = [grid '/120kV 2500MVA'];
if getSimulinkBlockHandle(old) == -1, fprintf('   [grid] source already replaced\n'); return; end
ph = get_param(old, 'PortHandles'); dst = cell(1, 3);
for k = 1:3
    l = get_param(ph.RConn(k), 'Line'); hs = [get_param(l, 'SrcPortHandle'), get_param(l, 'DstPortHandle')];
    hs = hs(hs ~= ph.RConn(k) & hs ~= -1); dst{k} = hs; delete_line(l);
end
pos = get_param(old, 'Position'); delete_block(old);
load_system('spsThreePhaseProgrammableVoltageSourceLib'); load_system('spsThreePhaseSeriesRLCBranchLib');
src = [grid '/120kV programmable']; br = [grid '/120kV source RL'];
add_block('spsThreePhaseProgrammableVoltageSourceLib/Three-Phase Programmable Voltage Source', src, 'Position', pos - [60 0 60 0], ...
    'PositiveSequence', '[120e3 0 Fnom+grid_df]', 'VariationEntity', 'Amplitude', 'VariationType', 'Step', 'VariationStep', 'grid_var_step', ...
    'VariationTiming', '[grid_var_t0 5]', 'HarmonicGeneration', 'on', 'HarmonicA', '[5 grid_h5 0 1]', 'HarmonicB', '[7 grid_h7 0 1]', 'Timing', '[grid_var_t0 5]');
% the popups (entity, harmonic generation) change the block's internal structure and would invalidate the operating-point
% snapshots, so they are fixed here and only the numeric parameters (grid_var_step, grid_df, grid_h5, grid_h7) vary per run
add_block('spsThreePhaseSeriesRLCBranchLib/Three-Phase Series RLC Branch', br, 'Position', pos + [30 0 30 0], 'BranchType', 'RL', 'Resistance', '0.8929', 'Inductance', '16.58e-3');
ps = get_param(src, 'PortHandles'); pb = get_param(br, 'PortHandles');
for k = 1:3
    add_line(grid, ps.RConn(k), pb.LConn(k)); for h = dst{k}, add_line(grid, pb.RConn(k), h); end
end
fprintf('   [grid] programmable source + RL branch in place of %s\n', old);
end
