function configure_ev_tcp(sampleRate, fftInputPort, fftOutputPort)
%CONFIGURE_EV_TCP Synchronize Iac with two independent TCP servers.
arguments
    sampleRate (1, 1) double {mustBePositive} = 4000
    fftInputPort (1, 1) double {mustBeInteger, mustBePositive} = 5002
    fftOutputPort (1, 1) double {mustBeInteger, mustBePositive} = 5003
end

model = "PV_MEV";
system = model + "/EV System";
sampleTime = "1/" + string(sampleRate);
load_system(model);
load_system("instrumentlib");

sourceBlock = system + "/From12";
conversionBlock = system + "/Data Type Conversion";
sampleHold = system + "/TCP Sample Hold";
mainSend = system + "/TCP//IP Send1";
mainReceive = system + "/TCP//IP Receive1";

% Iac runs at the electrical solver rate (5e-8 s). The TCP input and output
% must have one matching sample hit, otherwise thousands of stale responses
% accumulate between Receive calls.
if getSimulinkBlockHandle(sampleHold) == -1
    add_block("simulink/Discrete/Zero-Order Hold", sampleHold, ...
        "Position", [985, 2110, 1035, 2140]);
end
set_param(sampleHold, "SampleTime", sampleTime);

conversionPorts = get_param(conversionBlock, "PortHandles");
inputLine = get_param(conversionPorts.Inport(1), "Line");
if inputLine ~= -1
    sourcePort = get_param(inputLine, "SrcPortHandle");
    if get_param(sourcePort, "Parent") ~= getSimulinkBlockHandle(sampleHold)
        delete_line(inputLine);
    end
end
holdPorts = get_param(sampleHold, "PortHandles");
if get_param(holdPorts.Inport(1), "Line") == -1
    add_line(system, "From12/1", "TCP Sample Hold/1", ...
        "autorouting", "on");
end
if get_param(conversionPorts.Inport(1), "Line") == -1
    add_line(system, "TCP Sample Hold/1", "Data Type Conversion/1", ...
        "autorouting", "on");
end

set_param(conversionBlock, "OutDataTypeStr", "single");
set_param(mainSend, ...
    "Port", "5000", ...
    "ByteOrder", "little-endian", ...
    "EnableBlockingMode", "on", ...
    "Timeout", "10", ...
    "TransferDelay", "off", ...
    "Priority", "-10");
set_param(mainReceive, ...
    "Port", "5001", ...
    "DataSize", "[1, 1]", ...
    "DataType", "single", ...
    "ByteOrder", "little-endian", ...
    "EnableBlockingMode", "on", ...
    "Timeout", "10", ...
    "SampleTime", sampleTime, ...
    "Priority", "10");

fftSend = system + "/FFT TCP Send";
fftReceive = system + "/FFT Peak Receive";
fftDisplay = system + "/FFT Peak Hz";

if getSimulinkBlockHandle(fftSend) == -1
    add_block("instrumentlib/TCP//IP Send", fftSend, ...
        "Position", [1160, 2222, 1290, 2278]);
end
set_param(fftSend, ...
    "Host", "134.226.86.100", ...
    "Port", string(fftInputPort), ...
    "ByteOrder", "little-endian", ...
    "EnableBlockingMode", "on", ...
    "Timeout", "10", ...
    "TransferDelay", "off", ...
    "Priority", "-9");

if getSimulinkBlockHandle(fftReceive) == -1
    add_block("instrumentlib/TCP//IP Receive", fftReceive, ...
        "Position", [1160, 2307, 1290, 2363]);
end
set_param(fftReceive, ...
    "Host", "134.226.86.100", ...
    "Port", string(fftOutputPort), ...
    "DataSize", "[1, 1]", ...
    "DataType", "single", ...
    "ByteOrder", "little-endian", ...
    "EnableBlockingMode", "on", ...
    "Timeout", "10", ...
    "SampleTime", sampleTime, ...
    "Priority", "20");

if getSimulinkBlockHandle(fftDisplay) == -1
    add_block("simulink/Sinks/Display", fftDisplay, ...
        "Position", [1410, 2315, 1485, 2355]);
end

fftSendPorts = get_param(fftSend, "PortHandles");
if get_param(fftSendPorts.Inport(1), "Line") == -1
    add_line(system, "Data Type Conversion/1", "FFT TCP Send/1", ...
        "autorouting", "on");
end
fftReceivePorts = get_param(fftReceive, "PortHandles");
if get_param(fftReceivePorts.Outport(1), "Line") == -1
    add_line(system, "FFT Peak Receive/1", "FFT Peak Hz/1", ...
        "autorouting", "on");
end

save_system(model);
close_system(model);
close_system("instrumentlib", 0);
fprintf("EV TCP configured: Iac sampled at %g Hz; main 5000/5001; FFT %d/%d.\n", ...
    sampleRate, fftInputPort, fftOutputPort);
end
