Backend: Vitis
ClockPeriod: 10
ClockUncertainty: 27%
HLSConfig:
  Model:
    BitExact: true
    Precision: fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
InputShapes:
  waveform:
  - 80
  - 1
KerasModel: !keras_model 'fpga/estimator_hls4ml/keras_model.keras'
OutputDir: fpga/estimator_hls4ml
OutputPredictions: null
OutputShapes:
  layer34_out:
  - 8
Part: xczu7ev-ffvc1156-2-e
ProjectName: harmonic_estimator
Stamp: 61194d79
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
