"""Board versions: Vitis unified HLS components for the EMI detector and the HGQ2
harmonic estimator, in the same style as HLS_PRJ/mpcc (hls_config.cfg +
vitis-comp.json, s_axilite control bundle, xczu7ev, 10 ns).

    KERAS_BACKEND=torch python scripts/make_board_components.py [--out ../HLS_PRJ]

Each component is self-contained: the hls4ml firmware (bit_exact, generated by
hls4ml 1.3) is copied in, an AXI-Lite wrapper adds the parts that live outside
the network on the board (detector: (x-mu)*inv_sd standardization in float ->
ap_fixed<12,5> and the FA-budget thresholds -> flag bits; estimator: window
peak normalization and the decode to the legacy MPCC vector [A1,A3,A5,A7,
delta3,delta5,delta7]), and a C testbench checks the fixed-point network
against the host reference (detector: artifacts/detector_bitexact.onnx logits on the
dataset cycles; estimator: artifacts/onnx_reference_test_id.npz).  The same
testbench compiles with any C++17 compiler (scripts/csim_local.sh) because
hls4ml ships ap_types.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
PART = "xczu7ev-ffvc1156-2-e"


def carr(name, v, ctype="float"):
    body = ",\n    ".join(", ".join(f"{x:.9g}f" if ctype == "float" else str(x) for x in v[i:i + 6]) for i in range(0, len(v), 6))
    return f"static const {ctype} {name}[{len(v)}] = {{\n    {body}\n}};\n"


def write_cfg(comp: Path, top: str, syn_files, tb_files, weights_dir: str):
    lines = [f"part={PART}", "", "[hls]", "flow_target=vivado", "package.output.format=ip_catalog", "package.output.syn=false",
             "clock=10ns", "clock_uncertainty=27%", f"syn.top={top}"]
    cflags = f"-std=c++17 -Ifirmware -Ifirmware/nnet_utils -DWEIGHTS_DIR=\\\"{weights_dir}\\\""
    for f in syn_files:
        lines += [f"syn.file={f}", f"syn.file_cflags={f},{cflags}"]
    for f in tb_files:
        lines += [f"tb.file={f}", f"tb.file_cflags={f},{cflags}"]
    lines += ["tb.file=tb_data"]
    (comp / "hls_config.cfg").write_text("\n".join(lines) + "\n")
    json.dump({"name": comp.name, "type": "HLS", "configuration": {"componentType": "HLS", "configFiles": ["hls_config.cfg"], "work_dir": comp.name},
               "useSysrootToolchain": False, "template": "empty_hls_component"}, open(comp / "vitis-comp.json", "w"), indent=2)


def copy_firmware(src: Path, dst: Path):
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("*.pyc", "__pycache__"))
    # hls4ml's bundled ap_types are only used by the local (non-Vitis) C simulation; their forward declaration of
    # std::complex clashes with libc++'s inline namespace, so include <complex> instead.
    for h in ("ap_int_special.h", "ap_fixed_special.h"):
        f = dst / "ap_types" / h; t = f.read_text()
        t = t.replace("namespace std {\ntemplate<typename _Tp> class complex;\n}", "#include <complex>", 1); f.write_text(t)


# ----------------------------------------------------------------------------- detector
def make_detector(out: Path):
    comp = out / "emi_detector"; comp.mkdir(parents=True, exist_ok=True)
    copy_firmware(ROOT / "runs/det_v4/fpga/hls4ml/firmware", comp / "firmware")
    cfg = json.load(open(ROOT / "artifacts/detector.json"))
    mu = np.array(cfg["mu"], np.float32); inv = (1.0 / np.array(cfg["sd"], np.float32)).astype(np.float32)
    thr = np.array(cfg["thr"], np.float32); lthr = np.log(thr / (1 - thr)).astype(np.float32)
    n_in = len(cfg["features"])
    (comp / "emi_detector_axi.h").write_text(f"""#ifndef EMI_DETECTOR_AXI_H
#define EMI_DETECTOR_AXI_H
// EMI sensor-chain injection detector, board version (HGQ2 chain via hls4ml, bit_exact).
// Inputs : the {n_in} per-cycle features of EMI_DET_FPGA/src/emi_det/features.py (raw, float),
//          computed on the PS or by the feature block from the controller-internal signals.
// Outputs: 5 channel logits (Vdc, Vac, Iac, Vbat, Ibat) and flag bits (logit >= logit(thr)).
//          Persistence (2 consecutive cycles, as in the Simulink SIL block) is applied by the caller.
#define EMI_DET_N_IN {n_in}
#define EMI_DET_N_OUT 5
void emi_detector_axi(float feat[EMI_DET_N_IN], float logit[EMI_DET_N_OUT], unsigned int *flags);
#endif
""")
    (comp / "emi_detector_axi.cpp").write_text(f"""#include "emi_detector_axi.h"
#include "firmware/emi_detector.h"

// standardization constants from artifacts/detector.json (fit on the clean training cycles)
{carr("MU", mu)}
{carr("INV_SD", inv)}
// per-channel logit thresholds (1 % false-alarm budget, detector.json thr = {thr.tolist()})
{carr("LOGIT_THR", lthr)}

void emi_detector_axi(float feat[EMI_DET_N_IN], float logit[EMI_DET_N_OUT], unsigned int *flags) {{
#pragma HLS INTERFACE mode=s_axilite port=feat   bundle=control
#pragma HLS INTERFACE mode=s_axilite port=logit  bundle=control
#pragma HLS INTERFACE mode=s_axilite port=flags  bundle=control
#pragma HLS INTERFACE mode=s_axilite port=return bundle=control
    features_t x[EMI_DET_N_IN];
#pragma HLS ARRAY_PARTITION variable=x complete dim=0
    result_t y[EMI_DET_N_OUT];
#pragma HLS ARRAY_PARTITION variable=y complete dim=0
STD: for (int i = 0; i < EMI_DET_N_IN; ++i) {{
#pragma HLS UNROLL
        x[i] = features_t((feat[i] - MU[i]) * INV_SD[i]);   // float affine, then the network's input quantizer (RND/SAT)
    }}
    emi_detector(x, y);
    unsigned int f = 0;
OUT: for (int k = 0; k < EMI_DET_N_OUT; ++k) {{
#pragma HLS UNROLL
        float v = y[k].to_float();
        logit[k] = v;
        if (v >= LOGIT_THR[k]) f |= (1u << k);
    }}
    *flags = f;
}}
""")
    (comp / "tb_emi_detector.cpp").write_text(r"""// C testbench: fixed-point network vs the host reference logits (artifacts/detector_bitexact.onnx).
#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include "emi_detector_axi.h"

static bool read_rows(const char *path, int ncol, std::vector<std::vector<float> > &rows) {
    std::ifstream f(path); std::string line;
    if (!f) { std::printf("cannot open %s\n", path); return false; }
    while (std::getline(f, line)) {
        std::istringstream ss(line); std::vector<float> r(ncol); for (int i = 0; i < ncol; ++i) ss >> r[i]; rows.push_back(r);
    }
    return true;
}

int main() {
    std::vector<std::vector<float> > X, Y;
    if (!read_rows("tb_data/feat_raw.dat", EMI_DET_N_IN, X) || !read_rows("tb_data/ref_logits.dat", EMI_DET_N_OUT, Y)) return 1;
    std::ofstream fo("tb_data/csim_results.log");
    double maxerr = 0, sumsq = 0; int nflag_mismatch = 0, n = 0;
    for (size_t r = 0; r < X.size(); ++r) {
        float logit[EMI_DET_N_OUT]; unsigned int flags = 0;
        emi_detector_axi(&X[r][0], logit, &flags);
        unsigned int fref = 0;
        for (int k = 0; k < EMI_DET_N_OUT; ++k) {
            double e = std::fabs((double)logit[k] - Y[r][k]); if (e > maxerr) maxerr = e; sumsq += e * e; ++n;
            if (Y[r][k] >= std::log(0.05 / 0.95)) fref |= (1u << k);
            fo << logit[k] << (k + 1 < EMI_DET_N_OUT ? ' ' : '\n');
        }
        if (fref != flags) ++nflag_mismatch;
    }
    std::printf("emi_detector: %zu cycles  max |dlogit| %.4g  rms %.4g  flag-word mismatches %d\n", X.size(), maxerr, std::sqrt(sumsq / n), nflag_mismatch);
    return (maxerr < 0.05 && nflag_mismatch == 0) ? 0 : 2;
}
""")
    # reference vectors: dataset cycles (every 8th cycle, all sources) through the installed ONNX
    import onnxruntime as ort
    D = np.load(ROOT / "data/cycles_dataset.npz")
    X = np.nan_to_num(D["X"][::8, :n_in].astype(np.float32))
    s = ort.InferenceSession(str(ROOT / "artifacts/detector_bitexact.onnx"), providers=["CPUExecutionProvider"])
    L = np.asarray(s.run(None, {s.get_inputs()[0].name: X})[0], np.float32)
    (comp / "tb_data").mkdir(exist_ok=True)
    np.savetxt(comp / "tb_data/feat_raw.dat", X, fmt="%.8g"); np.savetxt(comp / "tb_data/ref_logits.dat", L, fmt="%.7g")
    write_cfg(comp, "emi_detector_axi", ["emi_detector_axi.cpp", "firmware/emi_detector.cpp"], ["tb_emi_detector.cpp"], "firmware/weights")
    (comp / "README.md").write_text(f"""# emi_detector (Vitis HLS component)

Board version of the EMI sensor-chain injection detector (`EMI_DET_FPGA/runs/det_v4`, HGQ2 QDense
{cfg['width']} chain, weights {cfg['wbits']} / activations {cfg['abits']} bits KIF, {cfg['params']} parameters), exported with
hls4ml 1.3 (Vitis backend, `bit_exact=True`, io_parallel, ReuseFactor 1) and wrapped like `HLS_PRJ/mpcc`:

- `emi_detector_axi(float feat[43], float logit[5], unsigned *flags)`, one `s_axilite` bundle `control`.
- Inputs are the raw 43 per-cycle features (`EMI_DET_FPGA/src/emi_det/features.py`); the wrapper applies the
  standardization `(x - mu) * inv_sd` in float and the network's input quantizer `ap_fixed<12,5,AP_RND,AP_SAT>`.
- Outputs: the 5 channel logits (Vdc, Vac, Iac, Vbat, Ibat) and `flags` bit k = logit_k >= logit(thr_k) with the
  1 % false-alarm thresholds of `artifacts/detector.json`. The 2-cycle persistence used by the Simulink SIL block is
  left to the caller (PS), so the IP is stateless.

Build (Vitis 2023.2+ unified flow, same as `mpcc`): open the component in Vitis, or

```
vitis-run --mode hls --cfg hls_config.cfg --work_dir emi_detector --csim   # tb_emi_detector.cpp vs tb_data/ref_logits.dat
vitis-run --mode hls --cfg hls_config.cfg --work_dir emi_detector --csynth
```

`tb_data/feat_raw.dat` holds {len(X)} dataset cycles (every 8th cycle of `data/cycles_dataset.npz`) and
`tb_data/ref_logits.dat` the host logits from `artifacts/detector_bitexact.onnx` (bit-exact export, scripts/export_bitexact_onnx.py); the testbench passes when the fixed-point
logits are within 0.05 and every flag word agrees. Local C simulation without Vitis: `EMI_DET_FPGA/scripts/csim_local.sh emi_detector`.
""")
    print("detector component:", comp, "tb rows", len(X))


# ----------------------------------------------------------------------------- estimator
def make_estimator(out: Path):
    comp = out / "harmonic_estimator"; comp.mkdir(parents=True, exist_ok=True)
    copy_firmware(ROOT / "fpga/estimator_hls4ml/firmware", comp / "firmware")
    (comp / "harmonic_estimator_axi.h").write_text("""#ifndef HARMONIC_ESTIMATOR_AXI_H
#define HARMONIC_ESTIMATOR_AXI_H
// HGQ2 Residual-BLS harmonic estimator (FFT_HGQ_BLS_FPGA contract), board version.
// Input : one grid cycle of the PFC current, 80 samples at 4 kHz (raw amperes; the wrapper normalizes by the window peak).
// Output: enc[8] = [c1,s1,c3,s3,c5,s5,c7,s7] (network output, normalized), peak (side channel), and the legacy
//         MPCC vector legacy[7] = [A1,A3,A5,A7,delta3,delta5,delta7] decoded as in harmonic_postprocess8_block
//         (ema_alpha = 1: the EMA, if wanted, is applied by the caller on enc[]).
#define HE_N_IN 80
#define HE_N_ENC 8
#define HE_N_LEGACY 7
void harmonic_estimator_axi(float wave[HE_N_IN], float enc[HE_N_ENC], float *peak, float legacy[HE_N_LEGACY]);
#endif
""")
    (comp / "harmonic_estimator_axi.cpp").write_text("""#include <cmath>
#include "harmonic_estimator_axi.h"
#include "firmware/harmonic_estimator.h"

static const float ORDER_SCALE[4] = {1.0f, 0.25f, 0.20f, 0.15f};
static const float ORDERS[3] = {3.0f, 5.0f, 7.0f};

void harmonic_estimator_axi(float wave[HE_N_IN], float enc[HE_N_ENC], float *peak, float legacy[HE_N_LEGACY]) {
#pragma HLS INTERFACE mode=s_axilite port=wave   bundle=control
#pragma HLS INTERFACE mode=s_axilite port=enc    bundle=control
#pragma HLS INTERFACE mode=s_axilite port=peak   bundle=control
#pragma HLS INTERFACE mode=s_axilite port=legacy bundle=control
#pragma HLS INTERFACE mode=s_axilite port=return bundle=control
    // CycleNorm: A = max(|x|, 1e-6), x_norm = x / A
    float A = 1e-6f;
PEAK: for (int i = 0; i < HE_N_IN; ++i) {
#pragma HLS PIPELINE
        float a = std::fabs(wave[i]); if (a > A) A = a;
    }
    float invA = 1.0f / A;
    waveform_t x[HE_N_IN];
#pragma HLS ARRAY_PARTITION variable=x complete dim=0
NORM: for (int i = 0; i < HE_N_IN; ++i) {
#pragma HLS UNROLL
        x[i] = waveform_t(wave[i] * invA);          // ap_fixed<8,3,AP_RND,AP_SAT>: the network's input quantizer
    }
    result_t y[HE_N_ENC];
#pragma HLS ARRAY_PARTITION variable=y complete dim=0
    harmonic_estimator(x, y);
    float amp[4], ph[4];
DEC: for (int h = 0; h < 4; ++h) {
#pragma HLS UNROLL
        float re = y[2 * h].to_float(), im = y[2 * h + 1].to_float();
        enc[2 * h] = re; enc[2 * h + 1] = im;
        amp[h] = A * ORDER_SCALE[h] * std::sqrt(re * re + im * im);
        ph[h] = std::atan2(im, re);
    }
    *peak = A;
    for (int h = 0; h < 4; ++h) legacy[h] = amp[h];
REL: for (int k = 0; k < 3; ++k) {
#pragma HLS UNROLL
        float rel = ph[k + 1] - ORDERS[k] * ph[0];
        legacy[4 + k] = std::atan2(std::sin(rel), std::cos(rel));
    }
}
""")
    (comp / "tb_harmonic_estimator.cpp").write_text(r"""// C testbench: fixed-point estimator vs the host reference (artifacts/onnx_reference_test_id.npz).
#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include "harmonic_estimator_axi.h"

static bool read_rows(const char *path, int ncol, std::vector<std::vector<float> > &rows) {
    std::ifstream f(path); std::string line;
    if (!f) { std::printf("cannot open %s\n", path); return false; }
    while (std::getline(f, line)) {
        std::istringstream ss(line); std::vector<float> r(ncol); for (int i = 0; i < ncol; ++i) ss >> r[i]; rows.push_back(r);
    }
    return true;
}

int main() {
    std::vector<std::vector<float> > X, Y, S;
    if (!read_rows("tb_data/wave_raw.dat", HE_N_IN, X) || !read_rows("tb_data/ref_enc.dat", HE_N_ENC, Y) || !read_rows("tb_data/ref_peak.dat", 1, S)) return 1;
    std::ofstream fo("tb_data/csim_results.log");
    double maxerr = 0, sumsq = 0, maxpk = 0; int n = 0;
    for (size_t r = 0; r < X.size(); ++r) {
        float enc[HE_N_ENC], peak, legacy[HE_N_LEGACY];
        harmonic_estimator_axi(&X[r][0], enc, &peak, legacy);
        double ep = std::fabs((double)peak - S[r][0]) / S[r][0]; if (ep > maxpk) maxpk = ep;
        for (int k = 0; k < HE_N_ENC; ++k) {
            double e = std::fabs((double)enc[k] - Y[r][k]); if (e > maxerr) maxerr = e; sumsq += e * e; ++n;
            fo << enc[k] << ' ';
        }
        fo << peak; for (int k = 0; k < HE_N_LEGACY; ++k) fo << ' ' << legacy[k]; fo << '\n';
    }
    std::printf("harmonic_estimator: %zu windows  max |denc| %.4g  rms %.4g  (output LSB 1/32 = 0.03125)  peak rel err %.3g\n",
                X.size(), maxerr, std::sqrt(sumsq / n), maxpk);
    return (maxerr <= 0.0625 && maxpk < 1e-5) ? 0 : 2;
}
""")
    R = np.load(ROOT.parent / "FFT_HGQ_BLS_FPGA/artifacts/onnx_reference_test_id.npz")
    x = R["x"].astype(np.float32); sc = R["scale"].astype(np.float32); y = R["y_onnx"].astype(np.float32)
    raw = x * sc[:, None]                                    # un-normalize: the wrapper redoes x / max|x|
    (comp / "tb_data").mkdir(exist_ok=True)
    np.savetxt(comp / "tb_data/wave_raw.dat", raw, fmt="%.8g"); np.savetxt(comp / "tb_data/ref_enc.dat", y, fmt="%.7g")
    np.savetxt(comp / "tb_data/ref_peak.dat", np.abs(raw).max(1), fmt="%.8g")
    write_cfg(comp, "harmonic_estimator_axi", ["harmonic_estimator_axi.cpp", "firmware/harmonic_estimator.cpp"], ["tb_harmonic_estimator.cpp"], "firmware/weights")
    (comp / "README.md").write_text(f"""# harmonic_estimator (Vitis HLS component)

Board version of the HGQ2 Residual-BLS harmonic estimator (`FFT_HGQ_BLS_FPGA`, 8-bit KIF, 30,664 parameters; the
model behind the MPCC_D_M1 / MPCC_D_H1 variants), exported with hls4ml 1.3 (Vitis backend, `bit_exact=True`,
io_parallel) from `EMI_DET_FPGA/fpga/estimator_hls4ml`, wrapped like `HLS_PRJ/mpcc`:

- `harmonic_estimator_axi(float wave[80], float enc[8], float *peak, float legacy[7])`, one `s_axilite` bundle `control`.
- `wave` is one grid cycle of the PFC current sampled at 4 kHz (raw amperes). The wrapper performs the contract's
  CycleNorm (`x / max|x|`, side channel `peak`) and the input quantizer `ap_fixed<8,3,AP_RND,AP_SAT>`.
- `enc` = `[c1,s1,c3,s3,c5,s5,c7,s7]` (network output); `legacy` = `[A1,A3,A5,A7,delta3,delta5,delta7]` decoded exactly as
  `harmonic_postprocess8_block` in `Simulation/PV_MEV/build_estimator.m` with `ema_alpha = 1` (apply the EMA on `enc` in
  the caller if wanted). `A3..A7`, `delta3..7` feed `mpcc_hls` (`use_harmonic = 1`); the FFT anchor / watchdog fusion
  (`hgq_fusion_alpha`, `hgq_min_ratio` in `init_paras.m`) stays on the PS.

Build (same flow as `mpcc`):

```
vitis-run --mode hls --cfg hls_config.cfg --work_dir harmonic_estimator --csim
vitis-run --mode hls --cfg hls_config.cfg --work_dir harmonic_estimator --csynth
```

`tb_data/` holds the {len(x)} ID windows of `FFT_HGQ_BLS_FPGA/artifacts/onnx_reference_test_id.npz` (un-normalized) with
the host ONNX outputs; the testbench passes when every output is within 2 LSB (0.0625) of the reference.
Local C simulation without Vitis: `EMI_DET_FPGA/scripts/csim_local.sh harmonic_estimator`.
""")
    print("estimator component:", comp, "tb rows", len(x))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--out", default=str(ROOT.parent / "HLS_PRJ")); a = ap.parse_args()
    make_detector(Path(a.out)); make_estimator(Path(a.out))
