function configure_fft_output(sampleTime, fftInputPort, fftOutputPort)
%CONFIGURE_FFT_OUTPUT Configure an independent FFT Send/Receive channel.

model = "ComTest";
load_system(model);
load_system("instrumentlib");

if nargin < 1 || isempty(sampleTime)
    sampleTime = get_param(model + "/TCP//IP Receive", "SampleTime");
else
    validateattributes(sampleTime, {"numeric"}, ...
        {"scalar", "positive", "finite"});
    sampleTime = string(sampleTime);
end
if nargin < 2 || isempty(fftInputPort)
    fftInputPort = 5002;
else
    validateattributes(fftInputPort, {"numeric"}, ...
        {"scalar", "integer", "positive", "finite"});
end
if nargin < 3 || isempty(fftOutputPort)
    fftOutputPort = 5003;
else
    validateattributes(fftOutputPort, {"numeric"}, ...
        {"scalar", "integer", "positive", "finite"});
end

fftSend = model + "/FFT TCP Send";
fftReceive = model + "/FFT Peak Receive";
fftDisplay = model + "/FFT Peak Hz";

if getSimulinkBlockHandle(fftSend) == -1
    add_block("instrumentlib/TCP//IP Send", fftSend, ...
        "Position", [380, 245, 510, 301]);
end
set_param(fftSend, ...
    "Host", "134.226.86.100", ...
    "Port", string(fftInputPort), ...
    "ByteOrder", "little-endian", ...
    "EnableBlockingMode", "on", ...
    "Timeout", "10", ...
    "TransferDelay", "off", ...
    "Priority", "-9");

if getSimulinkBlockHandle(fftReceive) == -1
    add_block("instrumentlib/TCP//IP Receive", fftReceive, ...
        "Position", [600, 245, 730, 301]);
end
set_param(fftReceive, ...
    "Host", "134.226.86.100", ...
    "Port", string(fftOutputPort), ...
    "DataSize", "[1, 1]", ...
    "DataType", "single", ...
    "ByteOrder", "little-endian", ...
    "EnableBlockingMode", "on", ...
    "Timeout", "10", ...
    "SampleTime", sampleTime, ...
    "Priority", "20");

sendPorts = get_param(fftSend, "PortHandles");
if get_param(sendPorts.Inport(1), "Line") == -1
    add_line(model, "Data Type Conversion/1", "FFT TCP Send/1", ...
        "autorouting", "on");
end

if getSimulinkBlockHandle(fftDisplay) == -1
    add_block("simulink/Sinks/Display", fftDisplay, ...
        "Position", [785, 250, 860, 290]);
end

receivePorts = get_param(fftReceive, "PortHandles");
if get_param(receivePorts.Outport(1), "Line") == -1
    add_line(model, "FFT Peak Receive/1", "FFT Peak Hz/1", ...
        "autorouting", "on");
end

save_system(model);
close_system(model);
close_system("instrumentlib", 0);
fprintf("FFT channel configured: input=%d, output=%d, Ts=%s s.\n", ...
    fftInputPort, fftOutputPort, sampleTime);
end
