cd('<RL4EV>/Simulation/PV_MEV'); addpath(pwd); load_system('PV_MEV'); d='PV_MEV/EV System/PFC Control/EMI Detector';
rt=sfroot; ch=rt.find('-isa','Stateflow.EMChart','Path',[d '/residual_score']);
ch.Script=sprintf(['function raw = residual_score(feat, par)\n%%#codegen\n' ...
 '%% joint-residual baseline of detector_eval_unified.py (export_residual.py): |x - med| / mad on six residual features,\n' ...
 '%% one logistic regression per channel; the same decision block, thresholds (RES.thr) and corrections follow.\n' ...
 'f = double(feat(:)''); med = par(7:12); mad = par(13:18); W = reshape(par(19:48), 6, 5); b = par(49:53);\n' ...
 'z = zeros(1, 6);\n' ...
 'for k = 1:6\n' ...
 '    i = min(48, max(1, round(par(k))));   %% feature index (1-based); res_par is all zeros when the network is the source\n' ...
 '    z(k) = abs(f(i) - med(k)) / max(mad(k), 1e-6);\n' ...
 'end\n' ...
 'lg = z * W + b;\n' ...
 'raw = single([lg, zeros(1, 10), zeros(1, 5)]);\n']);
rj=jsondecode(fileread('<RL4EV>/EMI_DET_FPGA/artifacts/residual.json')); assignin('base','RES',struct('thr',rj.thr(:)','par',rj.par(:)'));
assignin('base','VARIANT_NAME','MPCC_R6_RES'); evalin('base','init_paras'); set_param('PV_MEV','SimulationCommand','update'); fprintf('[compile MPCC_R6_RES] OK\n');
assignin('base','VARIANT_NAME','MPCC_R'); evalin('base','init_paras'); set_param('PV_MEV','SimulationCommand','update'); fprintf('[compile MPCC_R] OK\n');
save_system('PV_MEV'); close_system('PV_MEV',0); fprintf('[saved]\n');
